language: go
os:
  - linux
go:
  - 1.6.2
install:
  - go get github.com/Sirupsen/logrus
  - go get github.com/getblank/wango
  - go get github.com/spf13/cobra
  - go get github.com/mitchellh/gox
script: go get -t -v ./...
after_success:
  - gox -osarch="darwin/amd64"
  - curl --ftp-create-dirs --data-binary -k -T $HOME/gopath/bin/blank-fs -u $FTP_USER:$FTP_PASSWORD ftp://releases.getblank.net/releases/blank-fs/$(date +%Y-%m-%d_%H:%M)-$TRAVIS_OS_NAME/blank-fs
  - curl --ftp-create-dirs --data-binary -k -T $HOME/gopath/bin/blank-fs -u $FTP_USER:$FTP_PASSWORD ftp://releases.getblank.net/releases/blank-fs/$TRAVIS_OS_NAME/blank-fs
  - curl --ftp-create-dirs --data-binary -k -T ./blank-fs_darwin_amd64 -u $FTP_USER:$FTP_PASSWORD ftp://releases.getblank.net/releases/blank-fs/$(date +%Y-%m-%d_%H:%M)-osx/blank-fs
  - curl --ftp-create-dirs --data-binary -k -T ./blank-fs_darwin_amd64 -u $FTP_USER:$FTP_PASSWORD ftp://releases.getblank.net/releases/blank-fs/osx/blank-fs
